theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  projects:
    index:
      taxonomies:
        display: true
        layout: inline
        show_name: false
  image_sizes:
    sections:
      categories:
        hero:
          desktop:  1880
        hero_term:
          desktop:  1880
