theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: false
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  breadcrumb:
    position: none
  blocks:
    ignored: "block--class"
  projects:
    index:
      taxonomies:
        display: true
        layout: inline
        show_name: false
      options:
        categories: true
        image: true
        subtitle: true
        summary: false
        year: true

    share_links:
      enabled: false
    single:
      taxonomies:
        position: hero
        show_name: false
  image_sizes:
    blocks:
      gallery:
        grid:
          mobile:   450
          tablet:   700
          desktop:  800
    sections:
      categories:
        hero:
          desktop:  1880
        hero_term:
          desktop:  1880
      pages:
        hero:
          desktop:  1880
      projects:
        hero_single:
          desktop:  2400
